# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KWebRTCP2PDemo_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KWebRTCP2PDemo_swift

    pod 'GoogleWebRTC', '~> 1.1'
    pod 'Starscream', '~> 3.0'
    pod 'SnapKit', '~> 4.0.0'

  target 'KWebRTCP2PDemo_swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KWebRTCP2PDemo_swiftUITests' do
    # Pods for testing
  end

end
